package com.team6133.frc2018.auto;

public enum Destination {
    LEFT_SCALE, RIGHT_SCALE, LEFT_CORNER, RIGHT_CORNER, LEFT_SWITCH_FRONT, RIGHT_SWITCH_FRONT,
    LEFT_SWITCH_EDGE_NEAR, RIGHT_SWITCH_NEAR, LEFT_SWITCH_FAR, RIGHT_SWITCH_FAR
}
